language: node_js
node_js:
    - 10

before_install:
    - cd resources/travis
    - docker-compose up -d
    - cd ../..
    - sleep 10 # wait for zeebe to be ready

script: npm run test:integration

after_script:
    - cd resources/travis
    - docker-compose down
