version: '2'

services:
    zeebe:
        restart: always
        container_name: zeebe_broker
        image: camunda/zeebe:0.23.3
        environment:
            - ZEEBE_LOG_LEVEL=debug
        ports:
            - '26500:26500'
            - '9600:9600'
